<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/23
 * Time: 14:58
 */

namespace app\Controllers\CXK;


class Chat extends CXK
{
    public function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    //访问地址：http://localhost:8082/CXK/Chat
    public function http_Chat()
    {
        $configObject = getModuleConfig('common');
        $url = $configObject->get('webSocketConfig.url');//websocekt  服务器地址
        $template = $this->loader->view('app::CXK/chat');
        $data = [
            'title' => 'swoole聊天室例子',
            'url' => $url,
        ];
        $this->http_output->end($template->render($data));
    }
}