<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/22
 * Time: 20:12
 */

namespace app\Controllers\CXK;


use app\Controllers\BaseController;

class CXK extends BaseController
{
    public function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }
}