<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/23
 * Time: 14:58
 */

namespace app\Controllers\CXK;


class Index extends CXK
{
    public function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }


    public function http_Index()
    {
        $req = $this->http_input;
        $this->end($req);
        // controller(做数据验证等);
        // 加载model（数据处理） 测试
        $indexModel = $this->loader->model('CXK/Index', $this);
        $result = yield $indexModel->index("12121");
        return $this->end("result");
        // 测试 api 加载service（业务逻辑处理）
        $result = yield api('Kefu')->test();
        return $this->end($result);
    }
}